#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- include: check_install.yml

- include: _debian_install.yml
  when:
    ansible_os_family == 'Debian' and
    not ( mysql_is_major_upgrade | bool )

- include: _suse_install.yml
  when:
    ansible_os_family == 'Suse' and
    not ( mysql_is_major_upgrade | bool )

- include: stop.yml
  when:
    _debian_packages_installed_result.changed or
    _suse_packages_installed_result.changed or
    ( mysql_is_major_upgrade | bool )

- name: FND-MDB | install | Ensure restart xinetd
  become: yes
  meta: flush_handlers

- name: FND-MDB | install | Enable MDB services
  become: yes
  service:
    name: "{{ mysql_service }}"
    enabled: yes
