#
# (c) Copyright 2020 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Start mysql on these nodes. Note if the whole cluster is down
# this will not start as a boostrap will need to run on one node

---
- name: FND-MDB-monasca | configure | Check sever TLS cert
  become: yes
  stat:
    path: "{{ mysql_server_cert }}"
  register: mysql_server_cert_check_result

# NOTE(gyee): Since the provisioned TLS server certificate is consisted of
# both certificate and private key, we need to separate out the certificate
# protion for monitoring without having to compromise the private key.
# This is done by copying the certificate to a different file and make it
# readable by the world. Making certificate readable by the world is NOT a
# problem as it is TLS certificate is public information.
- name: FND-MDB-monasca | configure_tls | Separate out mysql TLS cert
  become: yes
  shell: >
    openssl x509 -in {{ mysql_server_cert }}
    -out {{ mysql_server_cert_monitoring }} -outform PEM
  when: mysql_server_cert_check_result.stat.exists

- name: FND-MBD-monasca | configure_tls |
        Make sure mysql TLS cert is readable
  become: yes
  file:
    path: "{{ mysql_server_cert_monitoring }}"
    mode: '0644'
  when: mysql_server_cert_check_result.stat.exists

- name: FND-MDB-monasca | configure_tls |
        Run Monasca detection plugin for mysql TLS certs
  become: yes
  monasca_agent_plugin:
    name: CertificateFileCheck
    args:
      cert_files: "{{ mysql_server_cert_monitoring }}"
      dimensions: "service:mysql"
  when: mysql_server_cert_check_result.stat.exists
